name: Test LTS-2024 Habitat Package Artifacts on PR

on:
  pull_request:

env:
  BLDR_URL: 'https://bldr.habitat.sh/'
  HAB_ORIGIN: 'chef'
  HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
  HABITAT_VERSION_SET: 'latest'
  CHEF_LICENSE: "accept-no-persist"
  HAB_LICENSE: "accept-no-persist"
  HAB_NONINTERACTIVE: "true"

permissions:
  contents: write

jobs:
  test-habitat-package:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS
        run: echo "--- ubuntu-latest"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install, Build, and Test Habitat Package (Linux)
        shell: bash
        env:
          HAB_REFRESH_CHANNEL: "LTS-2024"
          HAB_BLDR_CHANNEL: "LTS-2024"
        run: |
          echo "--- Installing Habitat on Linux with version: $HABITAT_VERSION_SET"
          curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v "$HABITAT_VERSION_SET" -t "x86_64-linux"
          
          hab license accept
          hab origin key download $HAB_ORIGIN
          hab origin key download --auth $HAB_AUTH_TOKEN --secret $HAB_ORIGIN
          
          hab pkg build .
          source results/last_build.env
          
          sudo hab license accept
          sudo hab pkg install results/$pkg_artifact
          
          
          # Patch Ruby scripts just for tests
          pkg_path=$(hab pkg path chef/knife-ec-backup)
          ruby_pkg=$(hab pkg path core/ruby3_1)   # or core/ruby3_2 depending on your gem's Ruby

          fix_interpreter "$pkg_path/bin/knife" "$ruby_pkg" bin/ruby
          fix_interpreter "$pkg_path/bin/rake" "$ruby_pkg" bin/ruby

          export PATH="$pkg_path/bin:$PATH"
          
          pushd "$PWD/test/artifact"
          rake
