name: Build and Publish Habitat Packages to LTS-2024-Current Channel

on: workflow_dispatch

env:
  BLDR_URL: 'https://bldr.habitat.sh/'
  HAB_ORIGIN: 'chef'
  HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
  HABITAT_VERSION_SET: 'latest'
  CHEF_LICENSE: "accept-no-persist"
  HAB_LICENSE: "accept-no-persist"
  HAB_NONINTERACTIVE: "true"

permissions:
  contents: write

jobs:
  agent-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS
        run: echo "--- ubuntu-latest"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Habitat
        shell: bash
        run: |
          echo "--- Installing Habitat on Linux with version: $HABITAT_VERSION_SET"
          curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v "$HABITAT_VERSION_SET" -t "x86_64-linux"

      - name: Build and Upload Habitat Package
        shell: bash
        env:
          HAB_REFRESH_CHANNEL: "LTS-2024"
          HAB_BLDR_CHANNEL: "LTS-2024"
        run: |
          hab license accept
          hab origin key download $HAB_ORIGIN
          hab origin key download --auth $HAB_AUTH_TOKEN --secret $HAB_ORIGIN
          hab pkg build .
          source results/last_build.env
          hab pkg upload --auth $HAB_AUTH_TOKEN results/$pkg_artifact --channel LTS-2024-current
          echo "--- push complete!!"
